[common]
platform  = espressif32
board     = esp32-c2-devkitm-1
framework = arduino

board_build.flash_size  = 4MB
board_upload.flash_size = 4MB
board_build.partitions  = min_spiffs.csv

;monitor_speed = 115200
monitor_speed = 500000
monitor_rts = 1
monitor_dtr = 1
lib_ldf_mode  = deep

lib_deps =
    adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.4
    adafruit/Adafruit GFX Library @ ^1.11.10
    bblanchon/ArduinoJson @ ^7.0.0

build_flags =
    -O3
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_ARCH_ESP32
    -DBOARD_C2_DUCO
    -I include
    -I "${platformio.packages_dir}/framework-arduinoespressif32/libraries/Network/src"
        ; --------------------------------------------------------
    ; Bekannte/nervige Compiler-Warnungen ausblenden
    ; Echte Fehler und andere wichtige Warnungen bleiben sichtbar
    ; --------------------------------------------------------
    -Wno-deprecated-declarations
    -Wno-write-strings

[env:esp32-c2-usb]
extends      = common
upload_protocol = esptool
upload_speed = 921600

[env:esp32-c2-ota]
extends         = common
upload_protocol = espota
upload_port     = 192.168.0.41
upload_flags    =
    --port=3232
    --auth=dasdaDadaDAsdsadaDASdd
